[package]
name = "rust-video"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jeresoftx/rust-video"
description = "Procesamiento de video en streaming con Rust para Jeresoft Academy."
readme = "README.md"

[lib]
name = "rust_video"
path = "src/lib.rs"

[dependencies]
